var tableData = [
    {
      // slno: It can be left blank. Slno is auto generated,
      CourseName: "Physics",
      subjectName: "Quantum Physics",
      topicName:"Simple Harmonic Oscillator",
      description: "1D SHO, Finding energy eigenfunction and eigen value. 3D SHO and degeneracy.",
      docLink:"<a href='http://galileo.phys.virginia.edu/classes/751.mf1i.fall02/SimpleHarmOsc.pdf'>PDF</a>",
      contributorName: "VB OCW Community",
      uploadDate:"Jan 1, 2022",
      dept: "Physics",
      courseLevel: "UG",
      InstructorName: "Dr. Swarup Kumar Majee",
      semYear: "Semester I, 2022",
      docId: "vbocw1",
    },
    {
      // slno:  It can be left blank. serialno is auto generated ,
      CourseName: "Physics",
      subjectName: "Nuclear & Particle Physics DSE",
      topicName:"Nuclear and particle physics",
      description: "All the topics taught in DSE physics course.",
      docLink:"<a href='https://drive.google.com/file/d/1vDdtAf318xQViaZnFwJuXt-HRtrx8MJb/view?usp=sharing'>PDF</a>",
      contributorName: "Arijit Das",
      uploadDate:"Jan 12, 2022",
      dept: "Physics",
      courseLevel: "UG",
      InstructorName: "Prof. Somenath Chakrabarty",
      semYear: "Semester V, 2020",
      docId: "vbocw2",
    },
    {
      // slno:  It can be left blank. serialno is auto generated ,
      CourseName: "Physics",
      subjectName: "Haskell-programming",
      topicName:"Distribution among energy level",
      description: "Code to study distribution of particles among energy levels.",
      docLink:"<a href='https://drive.google.com/file/d/1-kPqYLNF5Ep5OWnXrZpc-FBX0jiNbPkN/view?usp=sharing'>PDF</a>",
      contributorName: "Dr. Arani Chakrabarty",
      uploadDate:"Jan 12, 2022",
      dept: "Physics",
      courseLevel: "UG",
      InstructorName: "Dr. Arani Chakrabarty",
      semYear: "Semester VI, 2020",
      docId: "vbocw3",
    },
    {
      // slno:  It can be left blank. serialno is auto generated ,
      CourseName: "Physics",
      subjectName: "Haskell-programming",
      topicName:"Boson simulation",
      description: "Code to study distribution of Bosons among energy levels.",
      docLink:"<a href='https://drive.google.com/file/d/1eUWw_jNXeoEHFSOpMn_81c-y7wa83Exr/view?usp=sharing'>PDF</a>",
      contributorName: "Dr. Arani Chakrabarty",
      uploadDate:"Jan 12, 2022",
      dept: "Physics",
      courseLevel: "UG",
      InstructorName: "Dr. Arani Chakrabarty",
      semYear: "Semester VI, 2020",
      docId: "vbocw4",
    },
    {
      // slno:  It can be left blank. serialno is auto generated ,
      CourseName: "Physics",
      subjectName: "Haskell-programming",
      topicName:"Fermion simulation",
      description: "Code to study distribution of Fermions among energy levels.",
      docLink:"<a href='https://drive.google.com/file/d/19kjjgJhfF1enpwcG9hvg1YQybU8JIu_5/view?usp=sharing'>PDF</a>",
      contributorName: "Dr. Arani Chakrabarty",
      uploadDate:"Jan 12, 2022",
      dept: "Physics",
      courseLevel: "UG",
      InstructorName: "Dr. Arani Chakrabarty",
      semYear: "Semester VI, 2020",
      docId: "vbocw5",
    },
    {
      // slno:  It can be left blank. serialno is auto generated ,
      CourseName: "Physics",
      subjectName: "Haskell-programming",
      topicName:"Transition probablity",
      description: "Code to study distribution with transition probabilities.",
      docLink:"<a href='https://drive.google.com/file/d/1Q760xTxs70a00taWyFgNvMm5yqxrDtmY/view?usp=sharing'>PDF</a>",
      contributorName: "Dr. Arani Chakrabarty",
      uploadDate:"Jan 12, 2022",
      dept: "Physics",
      courseLevel: "UG",
      InstructorName: "Dr. Arani Chakrabarty",
      semYear: "Semester VI, 2020",
      docId: "vbocw6",
    },
    
]
